# Generated by Django 2.2.16 on 2020-10-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_profile_student_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
