# Generated by Django 2.2.16 on 2020-10-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="thisThat",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
