# Generated by Django 2.2.16 on 2020-10-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_thisthat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
